BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Filmy" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Tytul"	TEXT NOT NULL,
	"Ocena"	REAL NOT NULL,
	"IloscGlosow"	INTEGER NOT NULL,
	"Opis"	TEXT NOT NULL,
	"Plakat"	BLOB NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Rezerwacje" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UzytkownikID"	INTEGER NOT NULL,
	"SeansID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Seanse" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Sala"	INTEGER NOT NULL,
	"FilmID"	INTEGER NOT NULL,
	"Data"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Uzytkownicy" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Login"	TEXT NOT NULL UNIQUE,
	"Haslo"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
